# Generated by Django 3.2.25 on 2024-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=4)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
