# Generated by Django 3.2.5 on 2024-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
