# Generated by Django 3.2.25 on 2024-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_airport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
