# Generated by Django 3.2.5 on 2024-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
