# Generated by Django 3.2.25 on 2024-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0002_auto_20240707_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='non_smoking',
            field=models.BooleanField(default=False),
        ),
    ]
