# Generated by Django 3.2.5 on 2024-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0002_auto_20240807_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='availability',
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
