# Generated by Django 3.2.5 on 2024-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0002_property_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_bathroom',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image_kitchen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
