# Generated by Django 3.2.25 on 2024-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0003_auto_20240708_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
