# Generated by Django 3.2.5 on 2024-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0003_auto_20240722_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
