# Generated by Django 3.2.5 on 2024-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0003_alter_property_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
