# Generated by Django 3.2.5 on 2024-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0005_alter_property_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
