# Generated by Django 3.2.5 on 2024-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
