# Generated by Django 3.2.5 on 2024-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxi_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
