# Generated by Django 5.0.7 on 2024-07-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_properties', '0005_date_date_range_date_property_alter_date_id'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airbnb_properties.property')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
