# Generated by Django 3.2.5 on 2024-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_taxi_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxi_price',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='taxi_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
