# Generated by Django 3.2.5 on 2024-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240807_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='date_range',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
