# Generated by Django 3.2.5 on 2024-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20240720_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
