# Generated by Django 3.2.5 on 2024-08-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20240807_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='start_date',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='date_range',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
