# Generated by Django 3.2.5 on 2024-07-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='location',
        ),
    ]
