# Generated by Django 3.2.5 on 2024-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20240807_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
