# Generated by Django 3.2.5 on 2024-08-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20240807_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='date_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
