# Generated by Django 3.2.5 on 2024-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_orderlineitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
