# Generated by Django 3.2.5 on 2024-08-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_orderlineitem_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
