# Generated by Django 3.2.5 on 2024-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_orderlineitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='date_range',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
