# Generated by Django 3.2.25 on 2024-07-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='Faq',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='questions',
            new_name='question',
        ),
    ]
